[build]
  command = "make build-all"
  functions = "./functions"

[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/hmarr/grephub"
  GO111MODULE = "on"

